apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - backend
  - frontend

namespace: devops-app
namePrefix: prod-

images:
  - name: backend
    newName: ghcr.io/merlrwx/devops-app-api
    newTag: backend-v0.2.0
  - name: frontend
    newName: ghcr.io/merlrwx/devops-app-web
    newTag: frontend-v0.2.1
